### ISSUE TITLE
Bug with 2.1.20

### ISSUE THREAD

**Issue by aPaci95** [glutanimate/batch-editing#13]
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.20 (47a1bf8b) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-02-20 09:57:48

Caught exception:
Traceback (most recent call last):
  File "C:\Users\pacia\AppData\Roaming\Anki2\addons21\291119185\main.py", line 104, in <lambda>
    adda_btn.clicked.connect(lambda state, x="adda": self.onConfirm(x))
  File "C:\Users\pacia\AppData\Roaming\Anki2\addons21\291119185\main.py", line 186, in onConfirm
    batchEditNotes(browser, mode, nids, fld, text, isHtml=isHtml)
  File "C:\Users\pacia\AppData\Roaming\Anki2\addons21\291119185\main.py", line 224, in batchEditNotes
    mw.reset()
  File "aqt\main.py", line 634, in reset
  File "aqt\gui_hooks.py", line 933, in __call__
  File "lib\site-packages\anki\hooks.py", line 475, in runHook
  File "aqt\modelchooser.py", line 45, in onReset
  File "aqt\modelchooser.py", line 91, in updateModels
RuntimeError: wrapped C/C++ object of type QPushButton has been deleted

**Comment by glutanimate** [comment]
Thanks for the report! Closing this issue as outdated.
